"""
Purchase Order Management Tool

Manages purchase orders for Amazon FBA Replens inventory replenishment.
Works with POs auto-generated by Phase 5 forecasting (--auto-po) or
manually created via this tool.

Supports:
  - List POs with filtering by status and ASIN
  - Create manual POs (picks best supplier with real costs)
  - Confirm, ship, receive, cancel POs
  - Receive updates inventory and supplier reliability
  - Summary statistics for PO pipeline

Usage:
  uv run python tools/manage_orders.py list                        # List all POs
  uv run python tools/manage_orders.py list --status pending       # Filter by status
  uv run python tools/manage_orders.py list --asin B0BF5W643L     # Filter by ASIN
  uv run python tools/manage_orders.py create B0BF5W643L 50       # Create PO for 50 units
  uv run python tools/manage_orders.py confirm PO-20260312-XXXX   # Confirm a PO
  uv run python tools/manage_orders.py ship PO-20260312-XXXX      # Mark PO as shipped
  uv run python tools/manage_orders.py receive PO-20260312-XXXX   # Mark PO as received
  uv run python tools/manage_orders.py cancel PO-20260312-XXXX    # Cancel a PO
  uv run python tools/manage_orders.py summary                    # PO pipeline statistics
"""

import argparse
import logging
import sys
import uuid
from datetime import datetime, timedelta
from decimal import Decimal
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from src.database import (
    SessionLocal, Product, Supplier, ProductSupplier, PurchaseOrder, Inventory
)
from src.config import settings

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)

VALID_STATUSES = ["pending", "confirmed", "shipped", "received", "cancelled"]


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def generate_po_id():
    """Generate a unique PO ID with date prefix."""
    date_str = datetime.utcnow().strftime("%Y%m%d")
    short_uuid = uuid.uuid4().hex[:8].upper()
    return f"PO-{date_str}-{short_uuid}"


def format_currency(value):
    """Format a numeric value as currency string."""
    if value is None:
        return "$0.00"
    return f"${float(value):.2f}"


def format_date(dt):
    """Format a datetime for display, or return 'N/A'."""
    if dt is None:
        return "N/A"
    return dt.strftime("%Y-%m-%d %H:%M")


# ============================================================================
# LIST COMMAND
# ============================================================================

def cmd_list(args):
    """List purchase orders with optional filtering."""
    session = SessionLocal()
    try:
        query = session.query(PurchaseOrder)

        if args.status:
            if args.status not in VALID_STATUSES:
                logger.error(f"Invalid status '{args.status}'. Must be one of: {', '.join(VALID_STATUSES)}")
                return
            query = query.filter(PurchaseOrder.status == args.status)

        if args.asin:
            query = query.filter(PurchaseOrder.asin == args.asin)

        orders = query.order_by(PurchaseOrder.order_date.desc()).all()

        if not orders:
            logger.info("No purchase orders found matching the criteria.")
            return

        logger.info(f"Found {len(orders)} purchase order(s):\n")

        header = f"{'PO ID':<30} {'ASIN':<12} {'Supplier':<10} {'Qty':>6} {'Unit Cost':>10} {'Total':>12} {'Status':<12} {'Expected Delivery':<20}"
        print(header)
        print("-" * len(header))

        for po in orders:
            supplier_name = ""
            if po.supplier:
                supplier_name = po.supplier.name[:10]
            print(
                f"{po.po_id:<30} "
                f"{po.asin:<12} "
                f"{supplier_name:<10} "
                f"{po.quantity:>6} "
                f"{format_currency(po.unit_cost):>10} "
                f"{format_currency(po.total_cost):>12} "
                f"{po.status:<12} "
                f"{format_date(po.expected_delivery):<20}"
            )

        print()
        logger.info(f"Total: {len(orders)} order(s)")
    finally:
        session.close()


# ============================================================================
# CREATE COMMAND
# ============================================================================

def cmd_create(args):
    """Create a new purchase order for a product, picking the best supplier."""
    session = SessionLocal()
    try:
        # Validate product exists
        product = session.query(Product).filter(Product.asin == args.asin).first()
        if not product:
            logger.error(f"Product {args.asin} not found in database.")
            return

        # Find best supplier for this product
        # Prefer: is_preferred first, then lowest total_cost, then highest reliability
        product_suppliers = (
            session.query(ProductSupplier)
            .join(Supplier, ProductSupplier.supplier_id == Supplier.supplier_id)
            .filter(
                ProductSupplier.asin == args.asin,
                ProductSupplier.status == "active",
                Supplier.status == "active",
            )
            .order_by(
                ProductSupplier.is_preferred.desc(),
                ProductSupplier.total_cost.asc(),
            )
            .all()
        )

        if not product_suppliers:
            logger.error(f"No active suppliers found for ASIN {args.asin}. Add suppliers first.")
            return

        best_ps = product_suppliers[0]
        supplier = session.query(Supplier).filter(Supplier.supplier_id == best_ps.supplier_id).first()

        # Validate quantity against minimum order
        if supplier.min_order_qty and args.quantity < supplier.min_order_qty:
            logger.warning(
                f"Quantity {args.quantity} is below supplier minimum order quantity "
                f"of {supplier.min_order_qty}. Adjusting to minimum."
            )
            args.quantity = supplier.min_order_qty

        # Calculate costs from real supplier data
        unit_cost = best_ps.total_cost if best_ps.total_cost else best_ps.supplier_cost
        if unit_cost is None:
            logger.error(f"No cost data available for supplier {supplier.name} on ASIN {args.asin}.")
            return

        total_cost = Decimal(args.quantity) * Decimal(str(unit_cost))

        # Calculate expected delivery
        lead_time = supplier.lead_time_days if supplier.lead_time_days else 7
        expected_delivery = datetime.utcnow() + timedelta(days=lead_time)

        # Generate PO
        po_id = generate_po_id()
        po = PurchaseOrder(
            po_id=po_id,
            asin=args.asin,
            supplier_id=supplier.supplier_id,
            quantity=args.quantity,
            unit_cost=unit_cost,
            total_cost=total_cost,
            status="pending",
            order_date=datetime.utcnow(),
            expected_delivery=expected_delivery,
            notes=f"Manually created via manage_orders tool",
        )
        session.add(po)
        session.commit()

        logger.info(f"Purchase order created successfully:")
        logger.info(f"  PO ID:             {po_id}")
        logger.info(f"  ASIN:              {args.asin}")
        logger.info(f"  Product:           {product.title[:60] if product.title else 'N/A'}")
        logger.info(f"  Supplier:          {supplier.name} (ID: {supplier.supplier_id})")
        logger.info(f"  Quantity:          {args.quantity}")
        logger.info(f"  Unit Cost:         {format_currency(unit_cost)}")
        logger.info(f"  Total Cost:        {format_currency(total_cost)}")
        logger.info(f"  Expected Delivery: {format_date(expected_delivery)}")
    finally:
        session.close()


# ============================================================================
# CONFIRM COMMAND
# ============================================================================

def cmd_confirm(args):
    """Mark a purchase order as confirmed."""
    session = SessionLocal()
    try:
        po = session.query(PurchaseOrder).filter(PurchaseOrder.po_id == args.po_id).first()
        if not po:
            logger.error(f"Purchase order {args.po_id} not found.")
            return

        if po.status != "pending":
            logger.error(f"Cannot confirm PO {args.po_id}: current status is '{po.status}' (must be 'pending').")
            return

        po.status = "confirmed"
        po.last_updated = datetime.utcnow()
        session.commit()

        logger.info(f"Purchase order {args.po_id} confirmed.")
        logger.info(f"  ASIN:     {po.asin}")
        logger.info(f"  Quantity: {po.quantity}")
        logger.info(f"  Total:    {format_currency(po.total_cost)}")
    finally:
        session.close()


# ============================================================================
# SHIP COMMAND
# ============================================================================

def cmd_ship(args):
    """Mark a purchase order as shipped."""
    session = SessionLocal()
    try:
        po = session.query(PurchaseOrder).filter(PurchaseOrder.po_id == args.po_id).first()
        if not po:
            logger.error(f"Purchase order {args.po_id} not found.")
            return

        if po.status != "confirmed":
            logger.error(f"Cannot ship PO {args.po_id}: current status is '{po.status}' (must be 'confirmed').")
            return

        po.status = "shipped"
        po.last_updated = datetime.utcnow()
        session.commit()

        logger.info(f"Purchase order {args.po_id} marked as shipped.")
        logger.info(f"  ASIN:              {po.asin}")
        logger.info(f"  Quantity:          {po.quantity}")
        logger.info(f"  Expected Delivery: {format_date(po.expected_delivery)}")
    finally:
        session.close()


# ============================================================================
# RECEIVE COMMAND
# ============================================================================

def cmd_receive(args):
    """
    Mark a purchase order as received.
    Updates inventory stock levels and supplier on-time delivery rate.
    """
    session = SessionLocal()
    try:
        po = session.query(PurchaseOrder).filter(PurchaseOrder.po_id == args.po_id).first()
        if not po:
            logger.error(f"Purchase order {args.po_id} not found.")
            return

        if po.status not in ("confirmed", "shipped"):
            logger.error(
                f"Cannot receive PO {args.po_id}: current status is '{po.status}' "
                f"(must be 'confirmed' or 'shipped')."
            )
            return

        now = datetime.utcnow()

        # Update PO status
        po.status = "received"
        po.actual_delivery = now
        po.last_updated = now

        # --- Update Inventory ---
        inventory = session.query(Inventory).filter(Inventory.asin == po.asin).first()
        if inventory:
            inventory.current_stock = (inventory.current_stock or 0) + po.quantity
            inventory.available = (inventory.available or 0) + po.quantity
            inventory.last_restock_date = now
            inventory.last_updated = now

            # Recalculate needs_reorder
            reorder_point = inventory.reorder_point or 0
            inventory.needs_reorder = inventory.current_stock <= reorder_point

            logger.info(f"  Inventory updated for {po.asin}:")
            logger.info(f"    Current stock: {inventory.current_stock}")
            logger.info(f"    Available:     {inventory.available}")
            logger.info(f"    Needs reorder: {inventory.needs_reorder}")
        else:
            # Create inventory record if it doesn't exist
            inventory = Inventory(
                asin=po.asin,
                current_stock=po.quantity,
                reserved=0,
                available=po.quantity,
                last_restock_date=now,
                needs_reorder=False,
            )
            session.add(inventory)
            logger.info(f"  Created new inventory record for {po.asin} with {po.quantity} units.")

        # --- Update Supplier Reliability ---
        supplier = session.query(Supplier).filter(Supplier.supplier_id == po.supplier_id).first()
        if supplier:
            # Increment total orders
            old_total = supplier.total_orders or 0
            supplier.total_orders = old_total + 1

            # Determine if delivery was on time
            on_time = True
            if po.expected_delivery is not None:
                on_time = now <= po.expected_delivery

            # Update on_time_delivery_rate as running average
            old_rate = supplier.on_time_delivery_rate if supplier.on_time_delivery_rate is not None else 1.0
            if old_total > 0:
                # Weighted running average: ((old_rate * old_total) + new_value) / new_total
                supplier.on_time_delivery_rate = (
                    (old_rate * old_total) + (1.0 if on_time else 0.0)
                ) / supplier.total_orders
            else:
                supplier.on_time_delivery_rate = 1.0 if on_time else 0.0

            supplier.last_order_date = now
            supplier.last_updated = now

            delivery_status = "ON TIME" if on_time else "LATE"
            logger.info(f"  Supplier '{supplier.name}' updated:")
            logger.info(f"    Delivery: {delivery_status}")
            logger.info(f"    Total orders:         {supplier.total_orders}")
            logger.info(f"    On-time delivery rate: {supplier.on_time_delivery_rate:.1%}")

        session.commit()

        logger.info(f"Purchase order {args.po_id} received successfully.")
        logger.info(f"  ASIN:            {po.asin}")
        logger.info(f"  Quantity:        {po.quantity}")
        logger.info(f"  Actual Delivery: {format_date(po.actual_delivery)}")
    finally:
        session.close()


# ============================================================================
# CANCEL COMMAND
# ============================================================================

def cmd_cancel(args):
    """Cancel a purchase order."""
    session = SessionLocal()
    try:
        po = session.query(PurchaseOrder).filter(PurchaseOrder.po_id == args.po_id).first()
        if not po:
            logger.error(f"Purchase order {args.po_id} not found.")
            return

        if po.status in ("received", "cancelled"):
            logger.error(f"Cannot cancel PO {args.po_id}: current status is '{po.status}'.")
            return

        old_status = po.status
        po.status = "cancelled"
        po.last_updated = datetime.utcnow()
        session.commit()

        logger.info(f"Purchase order {args.po_id} cancelled (was '{old_status}').")
        logger.info(f"  ASIN:     {po.asin}")
        logger.info(f"  Quantity: {po.quantity}")
        logger.info(f"  Total:    {format_currency(po.total_cost)}")
    finally:
        session.close()


# ============================================================================
# SUMMARY COMMAND
# ============================================================================

def cmd_summary(args):
    """Show PO pipeline statistics."""
    session = SessionLocal()
    try:
        all_orders = session.query(PurchaseOrder).all()

        if not all_orders:
            logger.info("No purchase orders in the system.")
            return

        # Count by status
        status_counts = {}
        status_costs = {}
        for status in VALID_STATUSES:
            status_counts[status] = 0
            status_costs[status] = Decimal("0")

        total_cost_all = Decimal("0")
        total_qty_all = 0

        now = datetime.utcnow()
        week_end = now + timedelta(days=7)
        deliveries_this_week = []

        for po in all_orders:
            status_counts[po.status] = status_counts.get(po.status, 0) + 1
            cost = Decimal(str(po.total_cost)) if po.total_cost else Decimal("0")
            status_costs[po.status] = status_costs.get(po.status, Decimal("0")) + cost
            total_cost_all += cost
            total_qty_all += po.quantity or 0

            # Check for expected deliveries this week (for non-terminal POs)
            if po.status in ("pending", "confirmed", "shipped"):
                if po.expected_delivery and now <= po.expected_delivery <= week_end:
                    deliveries_this_week.append(po)

        print("\n" + "=" * 60)
        print("  PURCHASE ORDER SUMMARY")
        print("=" * 60)

        print(f"\n  Total Orders: {len(all_orders)}")
        print(f"  Total Units:  {total_qty_all}")
        print(f"  Total Cost:   {format_currency(total_cost_all)}")

        print(f"\n  {'Status':<14} {'Count':>6} {'Total Cost':>14}")
        print(f"  {'-'*14} {'-'*6} {'-'*14}")
        for status in VALID_STATUSES:
            count = status_counts[status]
            cost = status_costs[status]
            print(f"  {status:<14} {count:>6} {format_currency(cost):>14}")

        # Active pipeline (pending + confirmed + shipped)
        active_count = status_counts["pending"] + status_counts["confirmed"] + status_counts["shipped"]
        active_cost = status_costs["pending"] + status_costs["confirmed"] + status_costs["shipped"]
        print(f"\n  Active Pipeline: {active_count} orders, {format_currency(active_cost)} total")

        # Deliveries this week
        print(f"\n  Expected Deliveries This Week: {len(deliveries_this_week)}")
        if deliveries_this_week:
            for po in deliveries_this_week:
                print(
                    f"    - {po.po_id}  ASIN: {po.asin}  "
                    f"Qty: {po.quantity}  ETA: {format_date(po.expected_delivery)}  "
                    f"Status: {po.status}"
                )

        print("\n" + "=" * 60 + "\n")
    finally:
        session.close()


# ============================================================================
# MAIN / ARGPARSE
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Purchase Order Management Tool for Amazon FBA Replens",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  uv run python tools/manage_orders.py list
  uv run python tools/manage_orders.py list --status pending
  uv run python tools/manage_orders.py list --asin B0BF5W643L
  uv run python tools/manage_orders.py create B0BF5W643L 50
  uv run python tools/manage_orders.py confirm PO-20260312-A1B2C3D4
  uv run python tools/manage_orders.py ship PO-20260312-A1B2C3D4
  uv run python tools/manage_orders.py receive PO-20260312-A1B2C3D4
  uv run python tools/manage_orders.py cancel PO-20260312-A1B2C3D4
  uv run python tools/manage_orders.py summary
        """,
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # list
    list_parser = subparsers.add_parser("list", help="List purchase orders")
    list_parser.add_argument("--status", type=str, default=None, help="Filter by status (pending/confirmed/shipped/received/cancelled)")
    list_parser.add_argument("--asin", type=str, default=None, help="Filter by ASIN")

    # create
    create_parser = subparsers.add_parser("create", help="Create a new purchase order")
    create_parser.add_argument("asin", type=str, help="Product ASIN")
    create_parser.add_argument("quantity", type=int, help="Number of units to order")

    # confirm
    confirm_parser = subparsers.add_parser("confirm", help="Confirm a pending purchase order")
    confirm_parser.add_argument("po_id", type=str, help="Purchase order ID")

    # ship
    ship_parser = subparsers.add_parser("ship", help="Mark a purchase order as shipped")
    ship_parser.add_argument("po_id", type=str, help="Purchase order ID")

    # receive
    receive_parser = subparsers.add_parser("receive", help="Mark a purchase order as received (updates inventory and supplier stats)")
    receive_parser.add_argument("po_id", type=str, help="Purchase order ID")

    # cancel
    cancel_parser = subparsers.add_parser("cancel", help="Cancel a purchase order")
    cancel_parser.add_argument("po_id", type=str, help="Purchase order ID")

    # summary
    summary_parser = subparsers.add_parser("summary", help="Show PO pipeline statistics")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    commands = {
        "list": cmd_list,
        "create": cmd_create,
        "confirm": cmd_confirm,
        "ship": cmd_ship,
        "receive": cmd_receive,
        "cancel": cmd_cancel,
        "summary": cmd_summary,
    }

    logger.info(f"Running command: {args.command}")
    commands[args.command](args)


if __name__ == "__main__":
    main()
